### ISSUE TITLE
Add support for exporting final week schedule into iCalendar file

### ISSUE THREAD

**Issue by schullzroll** [kub05h/fitsch#1]
# Add support for exporting final week schedule into iCalendar file

## Currently...
- There is no export option for file formats other than the internal scheduler .json schedule dump (which isn't particularly useful outside of the sheduler)

## We want...
- To be able to easily export final schedule events with description into calendar/planning software such as Google Calendar, ios calendar, gnome-calendar, etc.

**(1) The export file format is open for discussion, but the main goal should be broad import compatibility across calendar apps.**

## Why...
- Because it will save a considerable amount of time for users that manually input finished scheduler events into calendar application.

- Because the whole process of week schedule planning will become less error prone for the end user, since the **exporter should automatically set description attributes like:**
    - from/to dates
    - number of occurences
    - room identification 
    - speakers name
    - event type
    - etc.

## Definition Of Done
- [ ] There is additional export button that allows user to download the finished schedule .ical(^1) file.

**Comment by kub05h** [comment]
Tos to nemoh napsat česky voe?

**Comment by schullzroll** [comment]
> Tos to nemoh napsat česky voe?

Třeba to dotáhne nějaký nečesky mluvící vývojáře 😏
